#!/bin/bash
nohup ~/python-2.6/virtenv/bin/python $OPENSHIFT_REPO_DIR/downloader.py > $OPENSHIFT_PYTHON_LOG_DIR/downloader 2>&1 &
nohup ~/python-2.6/virtenv/bin/python $OPENSHIFT_REPO_DIR/uploader.py > $OPENSHIFT_PYTHON_LOG_DIR/downloader 2>&1 &
